---
- name: Upgrade Ubuntu 22.04 to 23.10
  hosts: all
  become: yes
  tasks:
    - name: Update APT package index
      apt:
        update_cache: yes

    - name: Ensure update-manager-core is installed
      apt:
        name: update-manager-core
        state: present

    - name: Modify release-upgrades to normal
      lineinfile:
        path: /etc/update-manager/release-upgrades
        regexp: '^Prompt=.*'
        line: 'Prompt=normal'

    - name: Upgrade to Ubuntu 23.10
      command: do-release-upgrade -f DistUpgradeViewNonInteractive
      register: upgrade_output
      ignore_errors: yes

    - name: Reboot the server
      reboot:
        msg: "Rebooting the server to complete the upgrade"
        when: upgrade_output.rc == 0

